name: Nottingham_Bellringing
description: An app with inforamation about bellringing in Nottingham Distict.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.2
  http: "^0.11.3+16"
  xml: "^3.0.0"
  intl: "^0.15.6"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/Arnold.jpg
    - images/Aspley.jpg
    - images/Attenborough.jpg
    - images/Basford.jpg
    - images/Beeston.jpg
    - images/Bramcote.jpg
    - images/Bulwell.jpg
    - images/Daybrook.jpg
    - images/Lenton.jpg
    - images/Nottingham_All_Saints.jpg
    - images/Nottingham_St_Marys.jpg
    - images/Nottingham_St_Peters.jpg
    - images/Nuthall.jpg
    - images/Southall_Minster.jpg
    - images/Stapleford.jpg
    - images/Trowell.jpg
    - images/West_Bridgeford.jpg
    - images/Wollaton.jpg
