name: Nottingham_Bellringing
description: An app with inforamation about bellringing in Nottingham Distict.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.2
  http: "^0.11.3+16"
  xml: "^3.0.0"
  intl: "^0.15.6"
  path_provider: "^0.4.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lcov: "^4.0.0"

flutter:
  uses-material-design: true
  assets:
    - images/core/bellringing_logo.png
    - images/core/District_Logo.png
    - images/core/District_Main_Tower.jpg
    - images/towers/Arnold.jpg
    - images/towers/Aspley.jpg
    - images/towers/Attenborough.jpg
    - images/towers/Basford.jpg
    - images/towers/Beeston.jpg
    - images/towers/Bramcote.jpg
    - images/towers/Bulwell.jpg
    - images/towers/Daybrook.jpg
    - images/towers/Lenton.jpg
    - images/towers/Nottingham_All_Saints.jpg
    - images/towers/Nottingham_St_Marys.jpg
    - images/towers/Nottingham_St_Peters.jpg
    - images/towers/Nuthall.jpg
    - images/towers/Stapleford.jpg
    - images/towers/Trowell.jpg
    - images/towers/West_Bridgeford.jpg
    - images/towers/Wollaton.jpg