name: Nottingham_Bellringing
description: An app with inforamation about bellringing in Nottingham Distict.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.2
  http: "^0.11.3+16"
  xml: "^3.0.0"
  intl: "^0.15.6"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/SouthallMinster.jpg
    - images/NottinghamAllSaints.jpg
    - images/NottinghamStPeters.jpg
