import '../models/EventDetail.dart';

class EventList {
  static final List<EventDetail> eventList = [
    EventDetail(
      title: 'Bob Doubles Workshop',
      startTime: DateTime(2018, 7, 7, 10),
      location: 'Arnold',
      description: '',
      endTime: DateTime(2018, 7, 7, 12),
      dedication: 'S Mary',
      postcode: 'NG5 8HG',
      doveid: 'ARNOLD',
      posterLink: '',
    ),
    EventDetail(
      title: 'Bob Triples Workshop',
      startTime: DateTime(2018, 7, 7, 10),
      location: 'Attenborough',
      description: '',
      endTime: DateTime(2018, 7, 7, 12),
      dedication: 'S Mary V',
      postcode: 'NG9 6AS',
      doveid: 'ATTENBOROU',
      posterLink: '',
    ),
    EventDetail(
      title: 'Tower Practise',
      startTime: DateTime(2018, 8, 6, 19, 30),
      location: 'Aspley',
      description: '',
      endTime: DateTime(2018, 8, 6, 21),
      dedication: 'S Margaret',
      postcode: 'NG8 5JB',
      doveid: 'NOTTINGMAS',
      posterLink: '',
    ),
    EventDetail(
      title: 'Mini Outing',
      startTime: DateTime(2018, 9, 8, 10),
      location: 'Unknown',
      description: '',
      posterLink: '',
    ),
    EventDetail(
      title: 'District Meeting and Barn Dance',
      startTime: DateTime(2018, 10, 6, 16, 30),
      location: 'Nuthall',
      description: '',
      endTime: DateTime(2018, 10, 6, 22),
      dedication: 'S Patrick',
      postcode: 'NG16 1DT',
      doveid: 'NUTHALL',
      posterLink: '',
    ),
    EventDetail(
      title: 'District Meeting',
      startTime: DateTime(2018, 11, 3, 15, 30),
      location: 'Nottingham',
      description: '',
      endTime: DateTime(2018, 11, 3, 17, 00),
      dedication: 'All Saints',
      postcode: 'NG7 4DL',
      doveid: 'NOTTINGM+A',
      posterLink: '',
    ),
    EventDetail(
      title: 'District Meeting and Mince Pies',
      startTime: DateTime(2018, 12, 1, 16),
      location: 'Beeston',
      description: '',
      endTime: DateTime(2018, 12, 1, 18),
      dedication: 'S John Bapt',
      postcode: 'NG9 2JJ',
      doveid: 'BEESTON',
      posterLink: '',
    ),
    EventDetail(
      title: 'District Meeting and AGM',
      startTime: DateTime(2019, 1, 12, 15),
      location: 'Daybrook',
      description: '',
      endTime: DateTime(2019, 1, 12, 18),
      dedication: 'S Paul',
      postcode: 'NG5 6HW',
      doveid: 'DAYBROOK',
      posterLink: '',
    ),
    EventDetail(
      title: 'District Meeting',
      startTime: DateTime(2019, 2, 2, 15),
      location: 'Nottingham',
      description: '',
      endTime: DateTime(2019, 2, 2, 17),
      dedication: 'S Mary V',
      postcode: 'NG1 1PZ',
      doveid: 'NOTTINGM+M',
      posterLink: '',
    ),
    EventDetail(
      title: 'Crawford Cup Heat',
      startTime: DateTime(2019, 3, 9, 14, 30),
      location: 'Attenborough',
      description: '',
      endTime: DateTime(2019, 3, 9, 19),
      dedication: 'S Mary V',
      postcode: 'NG9 6AS',
      doveid: 'ATTENBOROU',
      posterLink: '',
    ),
  ];
}
