import '../models/TowerDetail.dart';

class TowerList {
  static final List<TowerDetail> towerList = [
    TowerDetail(
      place: "Arnold",
      dedication: "S Mary",
      numberOfBells: "8",
      weight: "8-2-9",
      postcode: "NG5 8HG",
      doveID: "ARNOLD",
      imageLocation: "images/towers/Arnold.jpg",
      practiseTime: "Thu 19:30-21:00",
      contactName: "Sue Baxter",
      phoneNumber: "0115 926 3134",
    ),
    TowerDetail(
      place: "Aspley",
      dedication: "S Margaret",
      numberOfBells: "8",
      weight: "9-1-15",
      postcode: "NG8 5JB",
      doveID: "NOTTINGMAS",
      imageLocation: "images/towers/Aspley.jpg",
      practiseTime: "Mon 19:30-21:00",
      serviceTime: "Sun 08:30-09:00",
      contactName: "Alan Robinson",
      email: "alan.robbo80@gmail.com",
    ),
    TowerDetail(
      place: "Attenborough",
      dedication: "S Mary V",
      numberOfBells: "8",
      weight: "11-0-21",
      postcode: "NG9 6AS",
      doveID: "ATTENBOROU",
      imageLocation: "images/towers/Attenborough.jpg",
      practiseTime: "Fri 19:30-21:00",
      serviceTime: "Sun 09:30-10:00 & 18:00-18:30",
      email: "bellringing@attenboroughchurch.org.uk",
    ),
    TowerDetail(
      place: "Basford",
      dedication: "S Leodegarius",
      numberOfBells: "8",
      weight: "14-3-0",
      postcode: "NG6 0GZ",
      doveID: "NOTTINGMBA",
      imageLocation: "images/towers/Basford.jpg",
      contactName: "Christopher Field",
      email: "basford@southwelldg.org.uk",
      phoneNumber: "07446388494",
    ),
    TowerDetail(
      place: "Beeston",
      dedication: "S John Bapt",
      numberOfBells: "10",
      weight: "17-1-14",
      postcode: "NG9 2JJ",
      doveID: "BEESTON",
      imageLocation: "images/towers/Beeston.jpg",
      practiseTime: "Wed 19:30-21:00",
      serviceTime: "Sun 09:15-10:00 & 17:50-1820 (Please check evening)",
      email: "beeston@southwelldg.org.uk",
    ),
    TowerDetail(
      place: "Bramcote",
      dedication: "S Michael & All Angels",
      numberOfBells: "6",
      weight: "5-1-14",
      postcode: "NG9 3HD",
      doveID: "BRAMCOTE",
      imageLocation: "images/towers/Bramcote.jpg",
      practiseTime: "Fri 19:30-21:00",
      serviceTime: "Sun 10:15-10:30 (Not 1st)",
      contactName: "Lesley Hill",
      phoneNumber: "0115 9164328",
    ),
    TowerDetail(
      place: "Bulwell",
      dedication: "S Mary V & All Souls",
      numberOfBells: "8",
      weight: "15-3-16",
      postcode: "NG6 9AE",
      doveID: "NOTTINGMBU",
      imageLocation: "images/towers/Bulwell.jpg",
      practiseTime: "Wed 19:30-21:00",
      serviceTime: "Sun 09:30-10:00",
      email: "bulwell@southwelldg.org.uk",
    ),
    TowerDetail(
      place: "Daybrook",
      dedication: "S Paul",
      numberOfBells: "8",
      weight: "9-2-3",
      postcode: "NG5 6HW",
      doveID: "DAYBROOK",
      imageLocation: "images/towers/Daybrook.jpg",
      practiseTime: "Fri 19:30-21:00",
      serviceTime: "Sun 09:00-09:30",
      contactName: "Sue Bellamy",
      email: "daybrook@outlook.com",
    ),
    TowerDetail(
      place: "Lenton",
      dedication: "Sacred & Undivided Trinity",
      numberOfBells: "8",
      weight: "8-0-2",
      postcode: "NG7 2FF",
      doveID: "NOTTINGMLE",
      imageLocation: "images/towers/Lenton.jpg",
      contactName: "John Berry",
      phoneNumber: "0115 914 7627 ",
    ),
    TowerDetail(
      place: "Nottingham",
      dedication: "All Saints",
      numberOfBells: "10",
      weight: "16-1-3",
      postcode: "NG7 4DL",
      doveID: "NOTTINGM+A",
      imageLocation: "images/towers/Nottingham_All_Saints.jpg",
      practiseTime: "Tue 19:00-20:30 (Term time only)",
      serviceTime: "Sun 10:00-10:30 (Term time only)",
      contactName: "NUSCR master",
      email: "master@nuscr.org",
    ),
    TowerDetail(
      place: "Nottingham",
      dedication: "S Mary V",
      numberOfBells: "12",
      weight: "35-2-23",
      postcode: "NG1 1PZ",
      doveID: "NOTTINGM+M",
      imageLocation: "images/towers/Nottingham_St_Marys.jpg",
      practiseTime: "Mon 19:30-21:00",
      serviceTime: "Sun 10:00-10:45 & 17:45-18:30",
      email: "nottinghamsmv@southwelldg.org.uk",
    ),
    TowerDetail(
      place: "Nottingham",
      dedication: "St Peters",
      numberOfBells: "12",
      weight: "22-2-5",
      postcode: "NG1 7DA",
      doveID: "NOTTINGM+P",
      imageLocation: "images/towers/Nottingham_St_Peters.jpg",
      practiseTime: "Thu 19:45-21:00",
      serviceTime: "Sun 16:00-17:00",
      email: "nottingham_st_peter@southwelldg.org.uk",
    ),
    TowerDetail(
      place: "Nuthall",
      dedication: "S Patrick",
      numberOfBells: "8",
      weight: "7-0-8",
      postcode: "NG16 1DT",
      doveID: "NUTHALL",
      imageLocation: "images/towers/Nuthall.jpg",
      practiseTime: "Tue 19:45-21:00",
      serviceTime: "Sun 09:30 (1st & 3rd) & 18:00 (2nd, 4th & 5th)",
      contactName: "Richard Doar",
      email: "rdoar@hotmail.com",
    ),
    TowerDetail(
      place: "Stapleford",
      dedication: "S Helen",
      numberOfBells: "6",
      weight: "7-1-7",
      postcode: "NG9 8GB",
      doveID: "STAPLEFRDN",
      imageLocation: "images/towers/Stapleford.jpg",
      practiseTime: "Mon 19:15-20:45",
      contactName: "Karen Barker",
      phoneNumber: "0115 946 0883 ",
    ),
    TowerDetail(
      place: "Trowell",
      dedication: "S Helen",
      numberOfBells: "6",
      weight: "9-1-0",
      postcode: "NG9 3QW",
      doveID: "TROWELL",
      imageLocation: "images/towers/Trowell.jpg",
      practiseTime: "Mon 19:30-21:00",
      serviceTime: "Sun 10:00-10:30",
      contactName: "Christine Bradshaw",
      email: "c.bradshaw833@ntlworld.com",
    ),
    TowerDetail(
      place: "West Bridgford",
      dedication: "S Giles",
      numberOfBells: "8",
      weight: "9-1-16",
      postcode: "NG2 6AZ",
      doveID: "WEST+BRIDG",
      imageLocation: "images/towers/West_Bridgeford.jpg",
      practiseTime: "Wed 19:45-21:15",
      serviceTime: "Sun 10:00-10:30 (1st only)",
      contactName: "Gary Harden",
      email: "g-harden@sky.com",
    ),
    TowerDetail(
      place: "Wollaton",
      dedication: "S Leonard",
      numberOfBells: "6",
      weight: "5-2-6",
      postcode: "NG8 2AF",
      doveID: "WOLLATON",
      imageLocation: "images/towers/Wollaton.jpg",
      practiseTime: "Thu 19:30-21:00",
      serviceTime: "Sun 09:30-10:00 & 17:30-18:00",
      contactName: "Carol Charmbury",
      phoneNumber: "0115 928 5008",
    ),
  ];
}
